# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "stop_watch", "~> 1.0"

gem "simple-random", "~> 1.0"
