# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "stop_watch", "~> 1.0"

gem "simple-random", "~> 1.0"

gem "faker", "~> 2.17"

gem "rspec", "~> 3.10"

gem "colorize", "~> 0.8.1"

gem "test-unit", "~> 3.4"
