# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "mac-say", "~> 0.2.1"

gem "thor", "~> 1.0"

gem "tty-prompt", "~> 0.21.0"
